# Site settings
title: "Musings"
description: "A blog"
baseurl: ""
url: "ashwins.dev"
author: "Ashwin S"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: 

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
