title: "Ashwin Sidhalinganahalli"
description: "Personal blog of Ashwin R S"
about: "I am a software developer working at Mobcrush. I like coding, biking and videogames."
location: "Santa Monica, California"
email: rsashwin@gmail.com
baseurl: ""
url: "http://ashwn.com"
twitter_username: rsashwin
github_username: ashwinrs
linkedin_username: ashwin.r.s

# google analytics tracking code, please change the value
g_analytics: "UA-85393178-1"

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "Posts"
imprint_btn: "Impressum"
name_badge: "Ashwin_nb"

# build settings
markdown: kramdown

# exclude files
exclude:
  - LICENSE
  - README.md
